import img1 from "./RollsImg/3 сыра запекуха.webp";
import img2 from "./RollsImg/gr6ln2pt0abpzsgofuomj6mcbc17s9ej.webp";
import img3 from "./RollsImg/zazr24nm9mq1ckvms4pu27532s0dowlv.webp";
import img4 from "./RollsImg/ztshscnhp3lwg5sfcar6v0z2kkdxq7dj.webp";
import img5 from "./RollsImg/РоллХрустящий.webp";
import img6 from "./RollsImg/акинава запеченная.webp";
import img7 from "./RollsImg/акинава запеченная.webp";
import img8 from "./RollsImg/горячая калифорния.webp";
import img9 from "./RollsImg/горячая филадельфия.webp";
import img10 from "./RollsImg/жареная с креветкой.webp";
import img11 from "./RollsImg/жареный американец.webp";
import img12 from "./RollsImg/запекуха с лососем.webp";
import img13 from "./RollsImg/ztshscnhp3lwg5sfcar6v0z2kkdxq7dj.webp";
import img14 from "./RollsImg/gr6ln2pt0abpzsgofuomj6mcbc17s9ej.webp";

export const RollsStorage = [
  {
    name: "РОЛЛ ХРУСТЯЩИЙ",
    structure:
      "Соус спайси, карпаччо, болгарский перец, огурец, лист салата, икра тобико",
    price: 299,
    src: img1,
    id: 1,
    weigth: "270",
    quantity: 8,
  },
  {
    name: "ФИЛАДЕЛЬФИЯ С ЗЕЛЁНЫМ ЛУКОМ",
    structure: "Сыр Филадельфия, Карпаччо, икра Тобико, Корнишоны",
    price: 299,
    src: img2,
    id: 2,
    weigth: "290",
    quantity: 8,
  },
  {
    name: "ИМПЕРАТОР С КРЕВЕТКОЙ",
    structure: "Сыр Филадельфия, Стружка Тунца, Копченный Кальмар, Огурец",
    price: 275,
    src: img3,
    id: 3,
    weigth: "280",
    quantity: 8,
  },
  {
    name: "ПРЕМИУМ С КРЕВЕТКОЙ",
    structure: "Тунец, сыр филадельфия, стружка тунца, огурец",
    price: 299,
    id: 4,
    src: img4,
    weigth: "300",
    quantity: 8,
  },
  {
    name: "СЛИВОЧНЫЙ С КОПЧЁНЫМ ЛОСОСЕМ (ЗАПЕЧЁННЫЙ)",
    structure: "Сыр Филадельфия, томаго, копченный кальмар, кунжут",
    price: 299,
    src: img5,
    id: 5,
    weigth: "280",
    quantity: 8,
  },
  {
    name: "ЗАПЕЧЁННЫЙ РОЛЛ 3 СЫРА",
    structure: "Сыр Филадельфия, икра тобико, снежный краб, унаги соус, кунжут",
    price: 275,
    src: img6,
    id: 6,
    weigth: "290",
    quantity: 8,
  },
  {
    name: "ГОРЯЧАЯ КАЛИФОРНИЯ",
    structure: "лосось, тунец, тобико, огурец, соус спайси",
    price: 335,
    src: img7,
    id: 7,
    weigth: "330",
    quantity: 8,
  },
  {
    name: "ГОРЯЧАЯ ФИЛАДЕЛЬФИЯ",
    structure: "лосось, огурец, сладкий перец, помидор, салат, майонез",
    price: 320,
    src: img8,
    id: 8,
    weigth: "330",
    quantity: 8,
  },
  {
    name: "ОКИНАВА",
    structure: "икра тобико, огурец, паприка, майонез, тунец",
    price: 355,
    src: img9,
    id: 9,
    weigth: "310",
    quantity: 8,
  },
  {
    name: "ИМПЕРАТОР",
    structure: "жареный лосось, тобико, кунжут, сыр филадельфия, огурец",
    price: 307,
    src: img10,
    id: 10,
    weigth: "320",
    quantity: 8,
  },
  {
    name: "ОСТРЫЙ С КРЕВЕТКОЙ",
    structure: "сыр филадельфия, икра тобико, томаго, кунжут, унаги соус",
    price: 290,
    src: img11,
    id: 11,
    weigth: "300",
    quantity: 8,
  },

  {
    name: "ФИЛАДЕЛЬФИЯ С ЗЕЛЁНЫМ ЛУКОМ",
    structure: "Сыр Филадельфия, Карпаччо, икра Тобико, Корнишоны",
    price: 299,
    src: img2,
    id: 12,
    weigth: "290",
    quantity: 8,
  },
  {
    name: "ИМПЕРАТОР С КРЕВЕТКОЙ",
    structure: "Сыр Филадельфия, Стружка Тунца, Копченный Кальмар, Огурец",
    price: 275,
    src: img3,
    id: 13,
    weigth: "280",
    quantity: 8,
  },
  {
    name: "ПРЕМИУМ С КРЕВЕТКОЙ",
    structure: "Тунец, сыр филадельфия, стружка тунца, огурец",
    price: 299,
    id: 14,
    src: img4,
    weigth: "300",
    quantity: 8,
  },
  {
    name: "СЛИВОЧНЫЙ С КОПЧЁНЫМ ЛОСОСЕМ (ЗАПЕЧЁННЫЙ)",
    structure: "Сыр Филадельфия, томаго, копченный кальмар, кунжут",
    price: 299,
    src: img5,
    id: 15,
    weigth: "280",
    quantity: 8,
  },
  {
    name: "ЗАПЕЧЁННЫЙ РОЛЛ 3 СЫРА",
    structure: "Сыр Филадельфия, икра тобико, снежный краб, унаги соус, кунжут",
    price: 275,
    src: img6,
    id: 16,
    weigth: "290",
    quantity: 8,
  },
  {
    name: "ГОРЯЧАЯ КАЛИФОРНИЯ",
    structure: "лосось, тунец, тобико, огурец, соус спайси",
    price: 335,
    src: img7,
    id: 17,
    weigth: "330",
    quantity: 8,
  },
  {
    name: "ГОРЯЧАЯ ФИЛАДЕЛЬФИЯ",
    structure: "лосось, огурец, сладкий перец, помидор, салат, майонез",
    price: 320,
    src: img8,
    id: 18,
    weigth: "330",
    quantity: 8,
  },
  {
    name: "ОКИНАВА",
    structure: "икра тобико, огурец, паприка, майонез, тунец",
    price: 355,
    src: img9,
    id: 19,
    weigth: "310",
    quantity: 8,
  },
  {
    name: "ИМПЕРАТОР",
    structure: "жареный лосось, тобико, кунжут, сыр филадельфия, огурец",
    price: 307,
    src: img10,
    id: 20,
    weigth: "320",
    quantity: 8,
  },
  {
    name: "ОСТРЫЙ С КРЕВЕТКОЙ",
    structure: "сыр филадельфия, икра тобико, томаго, кунжут, унаги соус",
    price: 290,
    src: img11,
    id: 21,
    weigth: "300",
    quantity: 8,
  },
  {
    name: "АЛЯСКА",
    structure: "сыр филадельфия, огурец, угорь, кунжут, тобико",
    price: 340,
    src: img12,
    id: 22,
    weigth: "315",
    quantity: 8,
  },
  {
    name: "ВУЛКАН",
    structure: "сыр филадельфия, огурец, угорь, кунжут, тобико",
    price: 350,
    src: img13,
    id: 23,
    weigth: "300",
    quantity: 8,
  },
  {
    name: "КАДЗАН",
    structure: "сыр филадельфия, огурец, угорь, кунжут, тобико",
    price: 340,
    src: img14,
    id: 24,
    weigth: "290",
    quantity: 8,
  },
  {
    name: "РОЛЛ ХРУСТЯЩИЙ",
    structure:
      "Соус спайси, карпаччо, болгарский перец, огурец, лист салата, икра тобико",
    price: 299,
    src: img1,
    id: 25,
    weigth: "270",
    quantity: 8,
  },
  {
    name: "ФИЛАДЕЛЬФИЯ С ЗЕЛЁНЫМ ЛУКОМ",
    structure: "Сыр Филадельфия, Карпаччо, икра Тобико, Корнишоны",
    price: 299,
    src: img2,
    id: 26,
    weigth: "290",
    quantity: 8,
  },
  {
    name: "ИМПЕРАТОР С КРЕВЕТКОЙ",
    structure: "Сыр Филадельфия, Стружка Тунца, Копченный Кальмар, Огурец",
    price: 275,
    src: img3,
    id: 27,
    weigth: "280",
    quantity: 8,
  },
  {
    name: "ПРЕМИУМ С КРЕВЕТКОЙ",
    structure: "Тунец, сыр филадельфия, стружка тунца, огурец",
    price: 299,
    id: 28,
    src: img4,
    weigth: "300",
    quantity: 8,
  },
  {
    name: "СЛИВОЧНЫЙ С КОПЧЁНЫМ ЛОСОСЕМ (ЗАПЕЧЁННЫЙ)",
    structure: "Сыр Филадельфия, томаго, копченный кальмар, кунжут",
    price: 299,
    src: img5,
    id: 29,
    weigth: "280",
    quantity: 8,
  },
  {
    name: "ЗАПЕЧЁННЫЙ РОЛЛ 3 СЫРА",
    structure: "Сыр Филадельфия, икра тобико, снежный краб, унаги соус, кунжут",
    price: 275,
    src: img6,
    id: 30,
    weigth: "290",
    quantity: 8,
  },
  {
    name: "ГОРЯЧАЯ КАЛИФОРНИЯ",
    structure: "лосось, тунец, тобико, огурец, соус спайси",
    price: 335,
    src: img7,
    id: 31,
    weigth: "330",
    quantity: 8,
  },
  {
    name: "ГОРЯЧАЯ ФИЛАДЕЛЬФИЯ",
    structure: "лосось, огурец, сладкий перец, помидор, салат, майонез",
    price: 320,
    src: img8,
    id: 32,
    weigth: "330",
    quantity: 8,
  },
  {
    name: "ОКИНАВА",
    structure: "икра тобико, огурец, паприка, майонез, тунец",
    price: 355,
    src: img9,
    id: 33,
    weigth: "310",
    quantity: 8,
  },
  {
    name: "ИМПЕРАТОР",
    structure: "жареный лосось, тобико, кунжут, сыр филадельфия, огурец",
    price: 307,
    src: img10,
    id: 34,
    weigth: "320",
    quantity: 8,
  },
  {
    name: "ОСТРЫЙ С КРЕВЕТКОЙ",
    structure: "сыр филадельфия, икра тобико, томаго, кунжут, унаги соус",
    price: 290,
    src: img11,
    id: 35,
    weigth: "300",
    quantity: 8,
  },

  {
    name: "ВУЛКАН",
    structure: "сыр филадельфия, огурец, угорь, кунжут, тобико",
    price: 350,
    src: img13,
    id: 36,
    weigth: "300",
    quantity: 8,
  },
  {
    name: "КАДЗАН",
    structure: "сыр филадельфия, огурец, угорь, кунжут, тобико",
    price: 340,
    src: img14,
    id: 37,
    weigth: "290",
    quantity: 8,
  },
  {
    name: "РОЛЛ ХРУСТЯЩИЙ",
    structure:
      "Соус спайси, карпаччо, болгарский перец, огурец, лист салата, икра тобико",
    price: 299,
    src: img1,
    id: 38,
    weigth: "270",
    quantity: 8,
  },
  {
    name: "ФИЛАДЕЛЬФИЯ С ЗЕЛЁНЫМ ЛУКОМ",
    structure: "Сыр Филадельфия, Карпаччо, икра Тобико, Корнишоны",
    price: 299,
    src: img2,
    id: 39,
    weigth: "290",
    quantity: 8,
  },
  {
    name: "ИМПЕРАТОР С КРЕВЕТКОЙ",
    structure: "Сыр Филадельфия, Стружка Тунца, Копченный Кальмар, Огурец",
    price: 275,
    src: img3,
    id: 40,
    weigth: "280",
    quantity: 8,
  },
];
